#!/usr/bin/env bash
# Shared helpers for the harness bootstrap. Sourced by install.sh and the
# per-agent modules. POSIX-bash; targets Linux and macOS (and WSL).

set -euo pipefail

# --- globals (populated by install.sh) ---------------------------------------
: "${REPO_ROOT:?REPO_ROOT must be set before sourcing common.sh}"
: "${DRY_RUN:=0}"
: "${TARGET_HOME:=$HOME}"
SELECTED_BUNDLES=()   # filled by install.sh
TS="$(date +%Y%m%d-%H%M%S)"

# --- logging -----------------------------------------------------------------
_c_reset='\033[0m'; _c_blue='\033[34m'; _c_yellow='\033[33m'; _c_red='\033[31m'; _c_green='\033[32m'
log()  { printf "${_c_blue}[harness]${_c_reset} %s\n" "$*"; }
ok()   { printf "${_c_green}[harness]${_c_reset} %s\n" "$*"; }
warn() { printf "${_c_yellow}[harness] warning:${_c_reset} %s\n" "$*" >&2; }
err()  { printf "${_c_red}[harness] error:${_c_reset} %s\n" "$*" >&2; }

# run CMD, or just print it under --dry-run.
run() {
  if [ "$DRY_RUN" = "1" ]; then
    printf "  would run: %s\n" "$*"
  else
    "$@"
  fi
}

# mkdir -p that respects dry-run.
ensure_dir() {
  [ -d "$1" ] && return 0
  run mkdir -p "$1"
}

# Back up an existing path before we overwrite it, unless it already points
# into this repo (i.e. a previous run of ours). Never deletes user data.
backup_path() {
  local p="$1"
  [ -e "$p" ] || [ -L "$p" ] || return 0
  if [ -L "$p" ]; then
    local tgt; tgt="$(readlink "$p" || true)"
    case "$tgt" in
      "$REPO_ROOT"/*) return 0 ;;  # our own symlink, leave it
    esac
  fi
  warn "backing up existing $p -> $p.bak.$TS"
  run mv "$p" "$p.bak.$TS"
}

# Symlink src->dst on POSIX; backs up any foreign file first, then force-creates
# (ln -sfn) so re-running over our own symlink is a clean no-op-ish replace.
link() {
  local src="$1" dst="$2"
  ensure_dir "$(dirname "$dst")"
  backup_path "$dst"
  run ln -sfn "$src" "$dst"
}

# Overwrite-copy into a directory we fully own (hook scripts, generated prompts).
# No backup: re-running just refreshes our own files, so .bak churn is avoided.
copy() {
  local src="$1" dst="$2"
  ensure_dir "$(dirname "$dst")"
  run cp -Rf "$src" "$dst"
}

# Is a bundle in the selected set?
bundle_selected() {
  local b
  for b in "${SELECTED_BUNDLES[@]}"; do
    [ "$b" = "$1" ] && return 0
  done
  return 1
}

# Link all SKILL.md skills (from selected bundles + every vendored source) into
# a destination skills directory. Used by agents that natively support the
# SKILL.md format (Claude, Antigravity). Vendored layouts differ: if a source's
# plugin.json declares an explicit "./skills/..." list (e.g. category-nested
# repos), honor exactly that; otherwise auto-discover every dir with a SKILL.md.
link_all_skills() {
  local dest="$1" b s src pj rel d f
  for b in "${SELECTED_BUNDLES[@]}"; do
    [ -d "$REPO_ROOT/bundles/$b/skills" ] || continue
    for s in "$REPO_ROOT/bundles/$b/skills"/*/; do
      [ -d "$s" ] || continue
      link "${s%/}" "$dest/$(basename "$s")"
    done
  done
  for src in "$REPO_ROOT/vendor"/*/; do
    [ -d "${src}skills" ] || continue
    pj="${src}.claude-plugin/plugin.json"
    if [ -f "$pj" ] && grep -q '"\./skills/' "$pj"; then
      while IFS= read -r rel; do
        d="${src}${rel#./}"
        [ -d "$d" ] || continue
        link "${d%/}" "$dest/$(basename "$d")"
      done <<EOF
$(grep -oE '"\./skills/[^"]+"' "$pj" | tr -d '"')
EOF
    else
      find "${src}skills" -type f -name 'SKILL.md' | while IFS= read -r f; do
        d="$(dirname "$f")"
        link "$d" "$dest/$(basename "$d")"
      done
    fi
  done
}

# Concatenate the rules/*.md of every selected bundle into a single managed
# block written to $1. Re-runnable: the whole file is regenerated each time.
assemble_rules() {
  local out="$1" b f
  ensure_dir "$(dirname "$out")"
  local tmp; tmp="$(mktemp)"
  {
    echo "<!-- BEGIN harness-managed rules. Generated by install.sh; edits here are overwritten. -->"
    echo "# Engineering rules (centralized)"
    echo
    for b in "${SELECTED_BUNDLES[@]}"; do
      [ -d "$REPO_ROOT/bundles/$b/rules" ] || continue
      for f in "$REPO_ROOT/bundles/$b/rules"/*.md; do
        [ -e "$f" ] || continue
        echo "<!-- source: bundles/$b/$(basename "$f") -->"
        cat "$f"
        echo
      done
    done
    echo "<!-- END harness-managed rules. -->"
  } > "$tmp"

  if [ "$DRY_RUN" = "1" ]; then
    printf "  would write assembled rules -> %s (%s lines)\n" "$out" "$(wc -l < "$tmp")"
    rm -f "$tmp"
  else
    # Only back up a pre-existing file we don't already manage, so re-runs
    # don't spawn a .bak every time.
    if ! grep -q "BEGIN harness-managed rules" "$out" 2>/dev/null; then
      backup_path "$out"
    fi
    mv "$tmp" "$out"
    ok "wrote $out"
  fi
}
