<#
.SYNOPSIS
  Bootstrap the centralized coding-agent configuration on native Windows.
.EXAMPLE
  .\install.ps1
  .\install.ps1 -Agent claude
  .\install.ps1 -Bundles core,backend-spring -DryRun
.NOTES
  Copies config (symlinks on Windows need admin/developer mode). Idempotent:
  re-run after `git pull`. Mirrors install.sh.
#>
[CmdletBinding()]
param(
  [string[]] $Agent,
  [string[]] $Bundles,
  [switch]   $DryRun
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$Stamp = Get-Date -Format 'yyyyMMdd-HHmmss'

function Log($m)  { Write-Host "[harness] $m" -ForegroundColor Blue }
function Ok($m)   { Write-Host "[harness] $m" -ForegroundColor Green }
function Warn($m) { Write-Warning "[harness] $m" }

function Backup-Path($p) {
  if (Test-Path $p) {
    Warn "backing up $p -> $p.bak.$Stamp"
    if (-not $DryRun) { Move-Item -Force $p "$p.bak.$Stamp" }
  }
}
function Copy-Into($src, $dst) {
  $parent = Split-Path -Parent $dst
  if (-not (Test-Path $parent)) { if (-not $DryRun) { New-Item -ItemType Directory -Force $parent | Out-Null } }
  Backup-Path $dst
  if ($DryRun) { Write-Host "  would copy $src -> $dst" } else { Copy-Item -Recurse -Force $src $dst }
}

# --- resolve bundles ---------------------------------------------------------
if (-not $Bundles) {
  $Bundles = Get-ChildItem -Directory (Join-Path $RepoRoot 'bundles') | ForEach-Object { $_.Name }
}
Log "bundles: $($Bundles -join ', ')"

# --- resolve agents ----------------------------------------------------------
if (-not $Agent) {
  $Agent = @()
  foreach ($a in 'claude','codex','opencode') {
    if (Get-Command $a -ErrorAction SilentlyContinue) { $Agent += $a }
  }
  if (-not $Agent) { Warn "no agent on PATH; defaulting to all three"; $Agent = @('claude','codex','opencode') }
}
Log "agents: $($Agent -join ', ')"
if ($DryRun) { Warn "dry-run: no files will be changed" }

function Assemble-Rules($outFile) {
  $lines = @('<!-- BEGIN harness-managed rules. Generated by install.ps1; edits here are overwritten. -->',
             '# Engineering rules (centralized)', '')
  foreach ($b in $Bundles) {
    $rdir = Join-Path $RepoRoot "bundles/$b/rules"
    if (Test-Path $rdir) {
      foreach ($f in Get-ChildItem -File "$rdir/*.md") {
        $lines += "<!-- source: bundles/$b/$($f.Name) -->"
        $lines += (Get-Content -Raw $f.FullName)
        $lines += ''
      }
    }
  }
  $lines += '<!-- END harness-managed rules. -->'
  if ($DryRun) { Write-Host "  would write assembled rules -> $outFile" ; return }
  $parent = Split-Path -Parent $outFile
  if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Force $parent | Out-Null }
  Backup-Path $outFile
  $lines -join "`n" | Set-Content -Encoding UTF8 $outFile
  Ok "wrote $outFile"
}

function Copy-BundleArtifacts($base, $agentsSub, $commandsSub) {
  foreach ($b in $Bundles) {
    $bd = Join-Path $RepoRoot "bundles/$b"
    if ($agentsSub -and (Test-Path "$bd/agents")) {
      foreach ($f in Get-ChildItem -File "$bd/agents/*.md") { Copy-Into $f.FullName (Join-Path $base "$agentsSub/$b-$($f.Name)") }
    }
    if ($commandsSub -and (Test-Path "$bd/commands")) {
      foreach ($f in Get-ChildItem -File "$bd/commands/*.md") { Copy-Into $f.FullName (Join-Path $base "$commandsSub/$b-$($f.Name)") }
    }
  }
}

function Install-Claude {
  $base = Join-Path $HOME '.claude'
  Assemble-Rules (Join-Path $base 'CLAUDE.md')
  Copy-BundleArtifacts $base 'agents' 'commands'
  foreach ($b in $Bundles) {
    $sk = Join-Path $RepoRoot "bundles/$b/skills"
    if (Test-Path $sk) { foreach ($d in Get-ChildItem -Directory $sk) { Copy-Into $d.FullName (Join-Path $base "skills/$($d.Name)") } }
  }
  $hsrc = Join-Path $RepoRoot 'bundles/core/hooks'
  if (Test-Path $hsrc) {
    foreach ($f in Get-ChildItem -File "$hsrc/*.sh") { Copy-Into $f.FullName (Join-Path $base "harness/hooks/$($f.Name)") }
    Warn "hooks copied to $base\harness\hooks; on Windows they need Git Bash/WSL to execute. Add them to $base\settings.json under hooks.PostToolUse/Stop."
  }
  Ok "Claude Code configured at $base"
  Write-Host "  Native marketplace alternative: claude plugin marketplace add <internal-gitlab-url>/coding-agent-harness-setup"
}

function Install-Codex {
  $base = Join-Path $HOME '.codex'
  Assemble-Rules (Join-Path $base 'AGENTS.md')
  Copy-BundleArtifacts $base $null 'prompts'
  $block = Join-Path $RepoRoot 'adapters/codex/config.toml'
  if (Test-Path $block) { Copy-Into $block (Join-Path $base 'config.harness.toml'); Warn "review $base\config.harness.toml and merge into config.toml" }
  Ok "Codex CLI configured at $base"
}

function Install-OpenCode {
  $base = Join-Path $HOME '.config/opencode'
  Assemble-Rules (Join-Path $base 'AGENTS.md')
  Copy-BundleArtifacts $base 'agent' 'command'
  $tmpl = Join-Path $RepoRoot 'adapters/opencode/opencode.json'
  if (Test-Path $tmpl) { Copy-Into $tmpl (Join-Path $base 'opencode.harness.json'); Warn "merge opencode.harness.json into opencode.json (set the format hook path)" }
  Ok "OpenCode configured at $base"
}

foreach ($a in $Agent) {
  switch ($a) {
    'claude'   { Log 'configuring claude ...';   Install-Claude }
    'codex'    { Log 'configuring codex ...';    Install-Codex }
    'opencode' { Log 'configuring opencode ...'; Install-OpenCode }
    default    { Warn "no module for agent '$a'; skipping" }
  }
}
Ok "done. Re-run after 'git pull' to update."
