#!/usr/bin/env bash
# GENERATED by scripts/build-plugins.py — prints this bundle's rules so Claude
# injects them as SessionStart additionalContext. Self-locating (no env var).
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cat "$DIR/../rules/"*.md
