#!/usr/bin/env python3
"""Generate the multi-agent plugin packaging from bundle sources.

This repo is a **plugin** for three coding agents — Claude Code, Codex, and
OpenCode. The canonical content lives in `bundles/<bundle>/` (rules, agents,
commands, skills, hooks). This script is the single source of truth that derives
every agent-specific packaging artifact from those bundles, so the content is
authored once and never hand-duplicated.

Run it whenever bundle content changes:

    python3 scripts/build-plugins.py            # write artifacts
    python3 scripts/build-plugins.py --check     # fail if artifacts are stale

Generated artifacts (DO NOT hand-edit — edit the bundle sources, then re-run):

  Claude Code (marketplace of bundles)
    .claude-plugin/marketplace.json
    bundles/<b>/.claude-plugin/plugin.json
  Codex (marketplace of bundles)
    .agents/plugins/marketplace.json
    bundles/<b>/.codex-plugin/plugin.json
  Cross-agent rules delivery
    bundles/<b>/AGENTS.md                      (OpenCode/Codex read this)
    bundles/<b>/skills/harness-rules-<b>/SKILL.md   (on-demand skill, all agents)
    bundles/<b>/hooks/hooks.json (+ inject-rules.sh)  (Claude always-on rules)
  OpenCode (project-scoped, zero installer — run `opencode` in this repo)
    AGENTS.md                                  (assembled global rules)
    opencode.json                              (lsp + mcp + instructions + plugin)
    .opencode/agents|commands|skills/...       (aggregated from all bundles)
    .opencode/plugins/superpowers.js           (link to vendored plugin)

A bundle's target agents follow its `bundles/<b>/adapters` file (one agent name
per line). No file = all three. `opencode`-only bundles get OpenCode wiring but
no Claude/Codex manifest (their agents drive `opencode run` + the ADO MCP).
"""
from __future__ import annotations

import json
import os
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BUNDLES = REPO / "bundles"
VERSION = "0.1.0"
AUTHOR = {"name": "coding-agent-harness", "url": "<internal-gitlab-url>/coding-agent-harness-setup"}
MARKETPLACE_NAME = "coding-agent-harness"
ALL_AGENTS = ["claude", "codex", "opencode"]

# Human-facing metadata per bundle. Keep descriptions one sentence.
BUNDLE_META = {
    "core": {
        "category": "review",
        "desc": "Core harness: always-on global coding rules, a local /code-review command, "
                "deterministic pre-commit + format/lint/test hooks, and a pre-PR review skill.",
    },
    "frontend-nextjs": {
        "category": "frontend",
        "desc": "Next.js 16 / React rules, a Next.js reviewer agent, and an App Router route scaffolder command.",
    },
    "backend-spring": {
        "category": "backend",
        "desc": "Spring Boot 3.5 rules and a Spring reviewer agent.",
    },
    "data-platform": {
        "category": "data",
        "desc": "Oracle/MariaDB and ClickHouse/MinIO rules and a SQL reviewer agent.",
    },
    "code-review": {
        "category": "review",
        "desc": "Unified review brain: a local-diff and Azure DevOps PR review skill plus a scheduled "
                "PR-reviewer agent. OpenCode-only (drives the Azure DevOps MCP).",
    },
    "azure-devops-prs": {
        "category": "automation",
        "desc": "Autonomous Azure DevOps PR babysitter agent + command for PRs you authored. "
                "OpenCode-only (drives the Azure DevOps MCP).",
    },
}

DO_NOT_EDIT = "<!-- GENERATED by scripts/build-plugins.py — do not hand-edit; edit bundle sources and re-run. -->\n"
_changed: list[str] = []
_check = "--check" in sys.argv[1:]


def bundles() -> list[str]:
    return [d.name for d in sorted(BUNDLES.iterdir()) if d.is_dir()]


def targets(bundle: str) -> list[str]:
    f = BUNDLES / bundle / "adapters"
    if not f.exists():
        return list(ALL_AGENTS)
    names = [ln.strip() for ln in f.read_text().splitlines()
             if ln.strip() and not ln.strip().startswith("#")]
    return [a for a in ALL_AGENTS if a in names]


def rule_files(bundle: str) -> list[Path]:
    d = BUNDLES / bundle / "rules"
    return sorted(d.glob("*.md")) if d.is_dir() else []


def write(path: Path, content: str) -> None:
    rel = path.relative_to(REPO)
    old = path.read_text() if path.exists() else None
    if old == content:
        return
    _changed.append(str(rel))
    if _check:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def write_json(path: Path, obj: dict) -> None:
    write(path, json.dumps(obj, indent=2) + "\n")


# --- Claude Code -------------------------------------------------------------
def gen_claude(bundle: str, meta: dict) -> None:
    write_json(BUNDLES / bundle / ".claude-plugin" / "plugin.json", {
        "name": f"harness-{bundle}",
        "version": VERSION,
        "description": meta["desc"],
        "author": AUTHOR,
        "keywords": ["coding-agent", "harness", meta["category"]],
    })


def gen_claude_marketplace(claude_bundles: list[str]) -> None:
    write_json(REPO / ".claude-plugin" / "marketplace.json", {
        "$schema": "https://anthropic.com/claude-code/marketplace.schema.json",
        "name": MARKETPLACE_NAME,
        "owner": AUTHOR,
        "description": "Centralized coding-agent harness: per-stack rules, reviewer subagents, "
                       "skills, and deterministic review/format hooks, as installable bundles.",
        "plugins": [
            {
                "name": f"harness-{b}",
                "source": f"./bundles/{b}",
                "description": BUNDLE_META[b]["desc"],
                "category": BUNDLE_META[b]["category"],
                "version": VERSION,
            } for b in claude_bundles
        ],
    })


# --- Codex -------------------------------------------------------------------
def gen_codex(bundle: str, meta: dict) -> None:
    manifest = {
        "name": f"harness-{bundle}",
        "version": VERSION,
        "description": meta["desc"],
        "author": AUTHOR,
    }
    if (BUNDLES / bundle / "skills").is_dir():
        manifest["skills"] = "./skills/"
    if (BUNDLES / bundle / "hooks" / "hooks.json").exists():
        manifest["hooks"] = "./hooks/hooks.json"
    write_json(BUNDLES / bundle / ".codex-plugin" / "plugin.json", manifest)


def gen_codex_marketplace(codex_bundles: list[str]) -> None:
    write_json(REPO / ".agents" / "plugins" / "marketplace.json", {
        "name": MARKETPLACE_NAME,
        "owner": AUTHOR,
        "description": "Centralized coding-agent harness bundles for Codex.",
        "plugins": [
            {
                "name": f"harness-{b}",
                "source": f"./bundles/{b}",
                "description": BUNDLE_META[b]["desc"],
                "version": VERSION,
            } for b in codex_bundles
        ],
    })


# --- Rules delivery (cross-agent) -------------------------------------------
RULE_SLUGS = {
    "core": ("harness-rules-core", "Always-on team coding standards (immutability, small files, error "
                                   "handling, security, testing). Consult before writing or reviewing any code."),
    "frontend-nextjs": ("harness-rules-nextjs", "Team rules for Next.js 16 / React. Consult before writing or "
                                                "reviewing frontend code."),
    "backend-spring": ("harness-rules-spring", "Team rules for Spring Boot 3.5. Consult before writing or "
                                               "reviewing backend Java code."),
    "data-platform": ("harness-rules-data", "Team rules for Oracle/MariaDB and ClickHouse/MinIO. Consult "
                                            "before writing or reviewing SQL / data-platform code."),
}


def assemble_rules(bundle: str) -> str:
    parts = [rf.read_text().rstrip() for rf in rule_files(bundle)]
    return "\n\n".join(parts) + "\n"


def gen_rules_artifacts(bundle: str) -> None:
    rfs = rule_files(bundle)
    if not rfs:
        return
    body = assemble_rules(bundle)

    # 1) AGENTS.md (OpenCode + Codex read this natively)
    write(BUNDLES / bundle / "AGENTS.md", DO_NOT_EDIT + "\n" + body)

    # 2) on-demand skill (all three agents; the only always-on path Codex plugins have)
    slug, desc = RULE_SLUGS[bundle]
    skill = f"---\nname: {slug}\ndescription: {desc}\n---\n\n{body}"
    write(BUNDLES / bundle / "skills" / slug / "SKILL.md", skill)

    # 3) Claude always-on: SessionStart hook that prints the rules
    inject = (
        "#!/usr/bin/env bash\n"
        "# GENERATED by scripts/build-plugins.py — prints this bundle's rules so Claude\n"
        "# injects them as SessionStart additionalContext. Self-locating (no env var).\n"
        'set -euo pipefail\n'
        'DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n'
        'cat "$DIR/../rules/"*.md\n'
    )
    hook_path = BUNDLES / bundle / "hooks" / "inject-rules.sh"
    write(hook_path, inject)
    if not _check:
        os.chmod(hook_path, 0o755)

    # merge SessionStart into hooks.json (preserve any existing hooks, e.g. core's)
    hj = BUNDLES / bundle / "hooks" / "hooks.json"
    cfg = json.loads(hj.read_text()) if hj.exists() else {"hooks": {}}
    cfg.setdefault("hooks", {})
    cfg["hooks"]["SessionStart"] = [{
        "matcher": "startup|resume",
        "hooks": [{
            "type": "command",
            "command": "${CLAUDE_PLUGIN_ROOT}/hooks/inject-rules.sh",
            "timeout": 5,
        }],
    }]
    write_json(hj, cfg)


# --- OpenCode (project-scoped) ----------------------------------------------
def gen_opencode(all_bundles: list[str]) -> None:
    # root AGENTS.md = global rules + pointer to stack bundles
    glob_rules = assemble_rules("core") if rule_files("core") else ""
    root_agents = (
        DO_NOT_EDIT + "\n# Coding-agent harness — global rules\n\n" + glob_rules +
        "\n> Stack-specific rules live in each bundle's `AGENTS.md` "
        "(`bundles/*/AGENTS.md`) and are wired via `instructions` in `opencode.json`.\n"
    )
    write(REPO / "AGENTS.md", root_agents)

    # opencode.json: lsp + format hook + instructions + mcp + plugin
    cfg = {
        "$schema": "https://opencode.ai/config.json",
        "instructions": ["AGENTS.md", "bundles/*/AGENTS.md"],
        "lsp": {
            "typescript": {
                "command": ["typescript-language-server", "--stdio"],
                "extensions": [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"],
            },
            "java": {"command": ["jdtls"], "extensions": [".java"]},
        },
        "experimental": {
            "hook": {
                "file_edited": {"*": [{"command": ["bundles/core/hooks/format.sh"]}]}
            }
        },
        "mcp": {
            "codegraph": {"type": "local", "command": ["codegraph", "serve", "--mcp"], "enabled": True},
            "azure-devops": {
                "type": "local",
                "command": ["npx", "-y", "@azure-devops/mcp", "YOUR_ADO_ORG"],
                "environment": {},
                "enabled": False,
            },
        },
    }
    write_json(REPO / "opencode.json", cfg)

    # aggregate bundle agents/commands/skills into .opencode/ (OpenCode = no globbing)
    oc = REPO / ".opencode"
    for kind, plural in (("agents", "agents"), ("commands", "commands")):
        dst = oc / plural
        if not _check and dst.exists():
            shutil.rmtree(dst)
        for b in all_bundles:
            src = BUNDLES / b / ("agents" if kind == "agents" else "commands")
            if src.is_dir():
                for f in sorted(src.glob("*.md")):
                    write(dst / f"{b}-{f.name}", f.read_text())
    # skills (keep skill dir name; prefix avoids collisions)
    sk_dst = oc / "skills"
    if not _check and sk_dst.exists():
        shutil.rmtree(sk_dst)
    for b in all_bundles:
        sdir = BUNDLES / b / "skills"
        if sdir.is_dir():
            for skill_dir in sorted(p for p in sdir.iterdir() if p.is_dir()):
                sm = skill_dir / "SKILL.md"
                if sm.exists():
                    write(sk_dst / skill_dir.name / "SKILL.md", sm.read_text())
    # superpowers JS plugin pointer (relative path note in INSTALL)
    sp = REPO / "vendor" / "superpowers" / ".opencode" / "plugins" / "superpowers.js"
    if sp.exists():
        write(oc / "plugins" / "superpowers.js",
              f"// GENERATED pointer. Re-export the vendored superpowers OpenCode plugin.\n"
              f"export * from \"../../vendor/superpowers/.opencode/plugins/superpowers.js\";\n")


def main() -> int:
    bs = bundles()
    claude_bundles, codex_bundles = [], []
    for b in bs:
        meta = BUNDLE_META.get(b)
        if not meta:
            print(f"WARN: no BUNDLE_META for bundle {b!r}; skipping", file=sys.stderr)
            continue
        tg = targets(b)
        gen_rules_artifacts(b)  # first: creates hooks.json the codex manifest points at
        if "claude" in tg:
            gen_claude(b, meta)
            claude_bundles.append(b)
        if "codex" in tg:
            gen_codex(b, meta)
            codex_bundles.append(b)
    gen_claude_marketplace(claude_bundles)
    gen_codex_marketplace(codex_bundles)
    gen_opencode(bs)

    if _check:
        if _changed:
            print("STALE generated artifacts (run scripts/build-plugins.py):")
            for c in _changed:
                print(f"  {c}")
            return 1
        print("plugin artifacts up to date.")
        return 0
    if _changed:
        print(f"wrote {len(_changed)} artifact(s):")
        for c in _changed:
            print(f"  {c}")
    else:
        print("no changes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
